# Generated by Django 4.0.4 on 2022-05-28 12:16

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockdata',
            name='field_one',
        ),
        migrations.RemoveField(
            model_name='mockdata',
            name='field_two',
        ),
        migrations.AddField(
            model_name='mockdata',
            name='json',
            field=jsonfield.fields.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='mockdata',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
